reconfigure: false
enabled: true
discord:
  serverID: <Server GuildID>
  serverName: <Server Name>
  token: <Bot Token>
  adminWhitelistRemoveRoleID:
    - <Role ID>
  adminWhitelistWhoisRoleID:
    - <Role ID>
  adminWhitelistBanRoleID:
    - <Role ID>
  whitelistServerRoleID:
    - <Role ID>
  embedErrorIcon: https://cdn.discordapp.com/emojis/841343837054173191.gif
  embedErrorAuthorURL: https://youtu.be/dQw4w9WgXcQ
  footerIcon: true
pterodactyl:
  enabled: true
  regexRemoveAnsi: "[\u001B\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\u0007)|(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))"
  APIKey: <Admin API KEY>
  panelURL: <Panel URL>
  whitelistAddCommand: whitelist add %v
  whitelistRemoveCommand: whitelist remove &v
  servers:
    - serverID: <Server ID>
      serverName: Main
      stateMessages:
        enabled: true
        start: ⚠️ Server is starting...
        stop: ⚠ Server is stopping...
        offline: ❌ Server is offline...
        online: ✅ Server is online!
        startEnabled: true
        stopEnabled: true
        offlineEnabled: true
        onlineEnabled: true
        channelID:
          - <Channel ID>
      channelInfo:
        enabled: true
        channelID:
          - <Channel ID>
        format: "{{onlineNumber}} players are Online | Server online for {{uptime}} | {{ram}} RAM | {{cpu}}% CPU | Server is {{state}} | Network in {{networkIn}} | Network out {{networkOut}}"
      powerActionsRoleIDs:
        start:
          - <Role ID>
        stop:
          - <Role ID>
        restart:
          - <Role ID>
      console:
        enabled: true
        messageLines: 10
        maxTimeInSeconds: 120
        channelID:
          - <Channel ID>
        reverse: true
        reverseRoleID:
          - <Role ID>
        reversePrefix: !
      chat:
        Enabled: true
        Embed: false
        Prefix: »(Server 1)
        ChannelID:
          - <Channel ID>
        embedFooter: false
        embedOneLine: true
        FooterIcon: true
        reverse: true
        roleID:
          - <Role ID>
      srv:
        Enabled: true
        OneLine: true
        Footer: false
        ChannelID:
          - <Channel ID>
        FooterIcon: true
        events:
          playerJoinLeft: true
          advancement: true
          rootAdvancements: false
          death: true
    - serverID: <Server ID>
      serverName: Farming
      stateMessages:
        enabled: true
        start: ⚠️ Server is starting...
        stop: ⚠ Server is stopping...
        offline: ❌ Server is offline...
        online: ✅ Server is online!
        startEnabled: true
        stopEnabled: true
        offlineEnabled: true
        onlineEnabled: true
        channelID:
          - <Channel ID>
      channelInfo:
        enabled: true
        channelID:
          - <Channel ID>
        format: "{{onlineNumber}} players are Online | Server online for {{uptime}} | {{ram}} RAM | {{cpu}}% CPU | Server is {{state}} | Network in {{networkIn}} | Network out {{networkOut}}"
      powerActionsRoleIDs:
        start:
          - <Role ID>
        stop:
          - <Role ID>
        restart:
          - <Role ID>
      console:
        enabled: true
        messageLines: 10
        maxTimeInSeconds: 120
        channelID:
          - <Channel ID>
        reverse: true
        reverseRoleID:
          - <Role ID>
        reversePrefix: !
      chat:
        Enabled: true
        Embed: false
        Prefix: »(Server 1)
        ChannelID:
          - <Channel ID>
        embedFooter: false
        embedOneLine: true
        FooterIcon: true
        reverse: true
        roleID:
          - <Role ID>
      srv:
        Enabled: true
        OneLine: true
        Footer: false
        ChannelID:
        events:
          playerJoinLeft: true
          advancement: true
          rootAdvancements: false
          death: true
    - serverID: <Server ID>
      serverName: Lobby
      channelInfo:
        enabled: true
        channelID:
          - <Channel ID>
        format: "{{onlineNumber}} players are Online | Server online for {{uptime}} | {{ram}} RAM | {{cpu}}% CPU | Server is {{state}} | Network in {{networkIn}} | Network out {{networkOut}}"
      stateMessages:
        enabled: true
        start: ⚠️ Server is starting...
        stop: ⚠ Server is stopping...
        offline: ❌ Server is offline...
        online: ✅ Server is online!
        startEnabled: true
        stopEnabled: true
        offlineEnabled: true
        onlineEnabled: true
        channelID:
          - <Channel ID>
      powerActionsRoleIDs:
        start:
          - <Role ID>
        stop:
          - <Role ID>
        restart:
          - <Role ID>
      console:
        enabled: true
        messageLines: 10
        maxTimeInSeconds: 120
        channelID:
          - <Channel ID>
        reverse: true
        reverseRoleID:
          - <Role ID>
        reversePrefix: !
      chat:
        Enabled: true
        Embed: false
        Prefix: »(Server 1)
        ChannelID:
          - <Channel ID>
        embedFooter: false
        embedOneLine: true
        FooterIcon: true
        reverse: true
        roleID:
          - <Role ID>
        events:
          playerJoinLeft: true
          advancement: true
          rootAdvancements: false
          death: true
      srv:
        Enabled: true
        OneLine: true
        Footer: false
        ChannelID:
          - <Channel ID>
        FooterIcon: true
srv:
  api:
    port: 8080
    user: admin_changeMe
    password: a$€cureP@55w0rd_4_Th3_API_ch@ngeM€
  states:
    online: 🟢 Online
    offline: 🔴 Offline
    starting: 🟡 Starting
    stopping: 🟠 Stopping
whitelist:
  enabled: true
  maxAccounts:
    - roleID: <RoleID>
      max: 6
    - roleID: <RoleID 2>
      max: 2
  bannedUsersToMaxAccounts: true
  kickUnWhitelisted: true
  kickCommand: kick %v Sorry, you are not whitelisted (anymore) on this server
  serverNames:
    - Farming
    - Main
    - Lobby
  mongodb:
    mongodbHost: <Database Host>
    mongodbPort: 1234
    mongodbUser: <Database User>
    mongodbPass: <Database Pass>
    mongodbDatabaseName: scharschbot
    mongodbWhitelistCollectionName: whitelist
    mongodbBanCollectionName: whitelistBans
    mongodbReWhitelistCollectionName: reWhitelist
    mongodbReportCollectionName: reports
  roles:
    serverRoleID:
      - <Role ID>
    removeUserWithout: true
    reWhitelistWith: true
    report:
      enabled: true
      channelID:
        - <Role ID>
      ping: true
      pingRoleID:
        - <Role ID>
      roles:
        - <Role ID>
      playerNotifyDM: true
      playerNotifyChannelID:
        - <Channel ID>
  luckperms:
    enabled: false
    setRole: <Whitelisted Role>
    databaseHost: <Database Host>
    databasePort: 1234
    databaseUser: <Database User>
    databasePass: <Database Pass>

