reconfigure: false
enabled: true
discord:
  serverID: <Server GuildID>
  token: <Bot Token>
  adminWhitelistRemoveRoleID: <Role ID>
  adminWhitelistWhoisRoleID: <Role ID>
  adminWhitelistBanID: <Role ID>
  whitelistServerRoleID: <Role ID>
  discordEmbedErrorIcon: https://cdn.discordapp.com/emojis/841343837054173191.gif
  embedErrorAuthorURL: https://youtu.be/dQw4w9WgXcQ
pterodactyl:
  enabled: true
  APIKey: <API KEY>
  PanelURL: <Panel URL>
  serverID: <server ID>
whitelist:
  enabled: true
  maxAccounts: 5
  mongodb:
    mongodbHost: <Database Host>
    mongodbPort: 1234
    mongodbUser: <Database User>
    mongodbPass: <Database Pass>
    mongodbDatabaseName: scharschbot
    mongodbCollectionName: whitelist
  roles:
    enabled: true
    serverRoleID: <role ID>
    removeRoleOthersID: <role ID>
    listUserRoleID: <role ID>
    whoisRoleID: <role ID>
    removeAllRoleID: <role ID>
    removeUserWithout: true
  luckperms:
    enabled: false
    setRole: <Whitelisted Role>
    databaseHost: <Database Host>
    databasePort: 1234
    databaseUser: <Database User>
    databasePass: <Database Pass>

