reconfigure: false
enabled: true
discord:
  serverID: <Server GuildID>
  token: <Bot Token>
whitelist:
  enabled: true
  maxAccounts: 5
  mongodb:
    mongodbHost: <Database Host>
    mongodbPort: 1234
    mongodbUser: <Database User>
    mongodbPass: <Database Pass>
    mongodbDatabaseName: scharschbot
    mongodbCollectionName: whitelist
  roles:
    enabled: true
    serverRoleID: <role ID>
    removeRoleOthersID: <role ID>
    listUserRoleID: <role ID>
    whoisRoleID: <role ID>
    removeAllRoleID: <role ID>
    removeUserWithout: true
  pterodactyl:
    enabled: true
    APIKey: <API KEY>
    PanelURL: <Panel URL>
    serverID: <server ID>
    whitelistCommand: whitelist {username}
  luckperms:
    enabled: false
    setRole: <Whitelisted Role>
    databaseHost: <Database Host>
    databasePort: 1234
    databaseUser: <Database User>
    databasePass: <Database Pass>

